### ISSUE TITLE
Screego does not contain UI when built from source

### ISSUE THREAD

**Issue by 0mp** [screego/server#31]
Hi,

what's the correct way of building Screego from source? I'm trying to add Screego to FreeBSD Ports, but the problem is that the binary I get does not contain the UI apparently. I've checked the official FreeBSD binaries you release, and they seem to work just fine by which I mean the website looks like the one on the demo site (after I configure screego.config and run `screego serve`, of course). With my manually built binaries, however, I get this kind of errors:

```
2020/10/09 17:45:02 http: panic serving 127.0.0.1:47506: stat /usr/home/user/f/ports/head/www/screego/build/index.html: no such file or directory
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc0000be000)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0xa93940, 0xc000390450)
        /usr/local/go/src/runtime/panic.go:975 +0x3e9
github.com/screego/server/ui.serveFile.func1(0x8289b6088, 0xc00038c1c0, 0xc0003b6100)
        /usr/home/0mp/f/ports/head/www/screego/work/server-1.0.5/ui/serve.go:34 +0x1fe
net/http.HandlerFunc.ServeHTTP(0xc0002f1b90, 0x8289b6088, 0xc00038c1c0, 0xc0003b6100)
        /usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc0003ac120, 0x8289b6088, 0xc00038c1c0, 0xc0003b6100)
        /usr/home/0mp/f/ports/head/www/screego/work/server-1.0.5/vendor/github.com/gorilla/handlers/cors.go:54 +0x103e
github.com/rs/zerolog/hlog.AccessHandler.func1.1(0xc0f0e0, 0xc0003b0000, 0xc0003b6100)
        /usr/home/0mp/f/ports/head/www/screego/work/server-1.0.5/vendor/github.com/rs/zerolog/hlog/hlog.go:196 +0x243
net/http.HandlerFunc.ServeHTTP(0xc00039a100, 0xc0f0e0, 0xc0003b0000, 0xc0003b6100)
        /usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000348000, 0xc0f0e0, 0xc0003b0000, 0xc0000c6000)
        /usr/home/0mp/f/ports/head/www/screego/work/server-1.0.5/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
net/http.serverHandler.ServeHTTP(0xc00018a1c0, 0xc0f0e0, 0xc0003b0000, 0xc0000c6000)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0000be000, 0xc10de0, 0xc000090080)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
zaz^C2020-10-09T17:45:09+02:00 INF Received interrupt. Shutting down...
```

What's the secret source needed to get the UI included in the binary?

Cheers!

**Comment by jmattheis** [comment]
Hey, I've added build docs: https://screego.net/#/development?id=build

**Comment by 0mp** [comment]
Thanks, I'll report back if I manage to get it going now :)

**Comment by jmattheis** [comment]
Oke, feel free to re-open the issue when there are any errors.
